return {
	{
		id = 0,
		name = "Air",
		unbreakable = true,
		replaceable = true,
		nonsolid = true,
		growreplaceable = true,
	},
	{
		id = 1,
		name = "Stone",
		hardness = 8,
		toughness = 1,
		tooltype = "pickaxe",
	},
	{
		id = 2,
		name = "Grass",
		hardness = 3,
		tooltype = "spade",
		growstree = true,
	},
	{
		id = 3,
		name = "Dirt",
		hardness = 3,
		tooltype = "spade",
		growstree = true,
		growscrops = true,
	},
	{
		id = 4,
		name = "Cobblestone",
		hardness = 6,
		toughness = 1,
		tooltype = "pickaxe",
	},
	{
		id = 5,
		name = "Wood",
		hardness = 6,
		tooltype = "axe",
	},
	{
		id = 6,
		name = "Sapling",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
		soiltick = true,
	},
	{
		id = 7,
		name = "Bedrock",
		unbreakable = true,
	},
	{
		id = 8,
		name = "Water",
		unbreakable = true,
		replaceable = true,
		fluid = true,
		drowning = true,
		level = 8,
		extinguishFire = true,
		nonsolid = true,
	},
	{
		id = 9,
		name = "Still water",
		unbreakable = true,
		replaceable = true,
		fluid = true,
		drowning = true,
		source = true,
		level = 8,
		extinguishFire = true,
		nonsolid = true,
	},
	{
		id = 10,
		name = "Lava",
		unbreakable = true,
		replaceable = true,
		fluid = true,
		level = 4,
		damage = 6,
		damageType = "lava",
		catchFire = true,
		nonsolid = true,
	},
	{
		id = 11,
		name = "Still lava",
		unbreakable = true,
		replaceable = true,
		fluid = true,
		source = true,
		level = 4,
		damage = 6,
		damageType = "lava",
		catchFire = true,
		nonsolid = true,
	},
	{
		id = 12,
		name = "Sand",
		hardness = 3,
		tooltype = "spade",
	},
	{
		id = 13,
		name = "Gravel",
		hardness = 3,
		tooltype = "spade",
	},
	{
		id = 14,
		name = "Gold ore",
		hardness = 24,
		toughness = 3,
		tooltype = "pickaxe",
	},
	{
		id = 15,
		name = "Iron ore",
		hardness = 16,
		toughness = 2,
		tooltype = "pickaxe",
	},
	{
		id = 16,
		name = "Coal ore",
		hardness = 12,
		toughness = 1,
		tooltype = "pickaxe",
	},
	{
		id = 17,
		name = "Log",
		hardness = 8,
		tooltype = "axe",
	},
	{
		id = 18,
		name = "Leaves",
		hardness = 2,
		tooltype = "axe",
		growreplaceable = true,
	},
	{
		id = 19,
		name = "Sponge",
		hardness = 3,
		tooltype = "spade",
	},
	{
		id = 20,
		name = "Glass",
		hardness = 2,
		tooltype = "pickaxe",
	},
	{
		id = 21,
		name = "Red",
	},
	{
		id = 22,
		name = "Orange",
	},
	{
		id = 23,
		name = "Yellow",
	},
	{
		id = 24,
		name = "Lime",
	},
	{
		id = 25,
		name = "Green",
	},
	{
		id = 26,
		name = "Teal",
	},
	{
		id = 27,
		name = "Aqua",
	},
	{
		id = 28,
		name = "Cyan",
	},
	{
		id = 29,
		name = "Blue",
	},
	{
		id = 30,
		name = "Indigo",
	},
	{
		id = 31,
		name = "Violet",
	},
	{
		id = 32,
		name = "Magenta",
	},
	{
		id = 33,
		name = "Pink",
	},
	{
		id = 34,
		name = "Black",
	},
	{
		id = 35,
		name = "Gray",
	},
	{
		id = 36,
		name = "White",
	},
	{
		id = 37,
		name = "Dandelion",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
	},
	{
		id = 38,
		name = "Rose",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
	},
	{
		id = 39,
		name = "Brown mushroom",
		consume = true,
		food = 1,
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
	},
	{
		id = 40,
		name = "Red mushroom",
		consume = true,
		food = 3,
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
	},
	{
		id = 41,
		name = "Gold",
		hardness = 24,
		toughness = 3,
		tooltype = "pickaxe",
	},
	{
		id = 42,
		name = "Iron",
		hardness = 16,
		toughness = 2,
		tooltype = "pickaxe",
	},
	{
		id = 43,
		name = "Double slab",
		hardness = 8,
		toughness = 1,
		tooltype = "pickaxe",
		parent = 44,
	},
	{
		id = 44,
		name = "Slab",
		hardness = 4,
		toughness = 1,
		tooltype = "pickaxe",
		mergeInto = 43,
		merger = 44,
		mergeFace = "AwayY",
		nonsolid = true,
		breakScale = "1.07 0.57 1.07",
	},
	{
		id = 45,
		name = "Bricks",
		hardness = 6,
		toughness = 1,
		tooltype = "pickaxe",
	},
	{
		id = 46,
		name = "TNT",
	},
	{
		id = 47,
		name = "Bookshelf",
		hardness = 6,
		tooltype = "axe",
	},
	{
		id = 48,
		name = "Mossy rocks",
		hardness = 9,
		toughness = 1,
		tooltype = "pickaxe",
	},
	{
		id = 49,
		name = "Obsidian",
		hardness = 60,
		toughness = 8,
		tooltype = "pickaxe",
	},
	{
		id = 50,
		name = "Magma",
		remainder = 10,
		hardness = 5,
		tooltype = "pickaxe",
	},
	{
		id = 51,
		name = "Coal",
		hardness = 12,
		toughness = 1,
		tooltype = "pickaxe",
	},
	{
		id = 52,
		name = "Diamond ore",
		hardness = 32,
		toughness = 3,
		tooltype = "pickaxe",
	},
	{
		id = 53,
		name = "Diamond",
		hardness = 32,
		toughness = 3,
		tooltype = "pickaxe",
	},
	{
		id = 54,
		name = "Fire",
		damage = 3,
		damageType = "fire",
		catchFire = true,
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 55,
		name = "Gold bar",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 56,
		name = "Iron bar",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 57,
		name = "Coal lump",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 58,
		name = "Diamond gem",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 59,
		name = "Stone brick",
		hardness = 8,
		tooltype = "pickaxe",
		toughness = 1,
	},
	{
		id = 60,
		name = "Ice",
		remainder = 8,
		hardness = 3,
		tooltype = "pickaxe",
	},
	{
		id = 61,
		name = "Workbench",
		hardness = 8,
		tooltype = "axe",
	},
	{
		id = 62,
		name = "Stonecutter",
		hardness = 8,
		tooltype = "pickaxe",
	},
	{
		id = 63,
		name = "Brown mushroom top",
		hardness = 4,
		tooltype = "spade",
	},
	{
		id = 64,
		name = "Red mushroom top",
		hardness = 4,
		tooltype = "spade",
	},
	{
		id = 65,
		name = "Mushroom stem",
		hardness = 8,
		tooltype = "spade",
	},
	{
		id = 66,
		name = "Stick",
	},
	{
		id = 67,
		name = "Campfire",
		hardness = 3,
		tooltype = "axe",
		attached = "y -1",
		nonsolid = true,
		breakScale = "0.65 0.5 0.65",
	},
	{
		id = 68,
		name = "Lit campfire",
		remainder = 67,
		damage = 3,
		damageType = "fire",
		catchFire = true,
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 69,
		name = "Cobweb",
		hardness = 5,
		tooltype = "spade",
		nonsolid = true,
	},
	{
		id = 70,
		name = "Lit torch",
		campfireLighter = 70,
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 71,
		name = "Snow",
		hardness = 2,
		tooltype = "spade",
	},
	{
		id = 72,
		name = "Snow ball",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 73,
		name = "Wood slab",
		hardness = 3,
		tooltype = "axe",
		mergeInto = 74,
		merger = 73,
		mergeFace = "AwayY",
		nonsolid = true,
		breakScale = "1.07 0.57 1.07",
	},
	{
		id = 74,
		name = "Double wood slab",
		hardness = 6,
		tooltype = "axe",
		parent = 73,
	},
	{
		id = 75,
		name = "Cobblestone slab",
		hardness = 3,
		touchness = 1,
		tooltype = "pickaxe",
		mergeInto = 76,
		merger = 75,
		mergeFace = "AwayY",
		nonsolid = true,
		breakScale = "1.07 0.57 1.07",
	},
	{
		id = 76,
		name = "Double cobblestone slab",
		hardness = 6,
		touchness = 1,
		tooltype = "pickaxe",
		parent = 75,
	},
	{
		id = 77,
		name = "Bread",
		consume = true,
		food = 8,
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 78,
		name = "Flax",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
	},
	{
		id = 79,
		name = "Wheat",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 80,
		name = "Torch",
		campfireLighter = 70,
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 81,
		name = "Compost pit",
		hardness = 6,
		tooltype = "pickaxe",
		nonsolid = true,
		breakScale = "1.07 0.57 1.07",
	},
	{
		id = 82,
		name = "Tombstone",
		hardness = 4,
		attached = "y -1",
		nonsolid = true,
		breakScale = "0.8 0.93 0.3",
		FaceEast = 94,
		FaceWest = 94,
	},
	{
		id = 83,
		name = "Sign",
		hardness = 8,
		tooltype = "axe",
	},
	{
		id = 84,
		name = "Pipe",
		hardness = 12,
		toughness = 3,
		tooltype = "pickaxe",
		nonsolid = true,
		FaceAwayX = 86,
		FaceTowardsX = 86,
		FaceAwayZ = 85,
		FaceTowardsZ = 85,
		breakScale = "0.55 1.07 0.55",
	},
	{
		id = 85,
		name = "Pipe-Z",
		hardness = 12,
		toughness = 3,
		tooltype = "pickaxe",
		nonsolid = true,
		breakScale = "0.55 0.8 1.07",
		parent = 84,
	},
	{
		id = 86,
		name = "Pipe-X",
		hardness = 12,
		toughness = 3,
		tooltype = "pickaxe",
		nonsolid = true,
		breakScale = "1.07 0.8 0.55",
		parent = 84,
	},
	{
		id = 87,
		name = "Cage",
		hardness = 20,
		toughness = 6,
		tooltype = "pickaxe",
	},
	{
		id = 88,
		name = "Soil",
		hardness = 3,
		tooltype = "spade",
		growstree = true,
		growscrops = true,
		growsflowers = true,
		growsmushrooms = true,
	},
	{
		id = 89,
		name = "Seeds",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
		soiltick = true,
	},
	{
		id = 90,
		name = "Wheat crop stage 1",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
		soiltick = true,
		parent = 89,
	},
	{
		id = 91,
		name = "Wheat crop stage 2",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
		soiltick = true,
		parent = 89,
	},
	{
		id = 92,
		name = "Wheat crop stage 3",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
		soiltick = true,
		parent = 89,
	},
	{
		id = 93,
		name = "Wheat crop stage 4",
		attached = "y -1",
		nonsolid = true,
		growreplaceable = true,
		parent = 89,
	},
	{
		id = 94,
		name = "Tombstone-NS",
		hardness = 4,
		attached = "y -1",
		nonsolid = true,
		breakScale = "0.3 0.93 0.8",
		parent = 82,
	},
	{
		id = 95,
		name = "Flower stem",
		hardness = 8,
		tooltype = "axe",
	},
	{
		id = 96,
		name = "Thorn",
		attached = "y -1",
		nonsolid = true,
		FaceTowardsY = 97,
		damage = 4,
		damageType = "thorn",
		mineDamage = 4,
		hardness = 6,
		toughness = 1,
		tooltype = "axe",
	},
	{
		id = 97,
		name = "Thorn-U",
		attached = "y 1",
		nonsolid = true,
		parent = 96,
		damage = 4,
		damageType = "thorn",
		mineDamage = 4,
		hardness = 6,
		toughness = 1,
		tooltype = "axe",
	},
	{
		id = 98,
		name = "Mycelium",
		hardness = 5,
		tooltype = "spade",
		growsmushrooms = true,
	},
	{
		id = 99,
		name = "Sandstone",
		hardness = 6,
		toughness = 1,
		tooltype = "pickaxe",
	},
	{
		id = 100,
		name = "Sandstone slab",
		hardness = 3,
		touchness = 1,
		tooltype = "pickaxe",
		mergeInto = 101,
		merger = 100,
		mergeFace = "AwayY",
		nonsolid = true,
		breakScale = "1.07 0.57 1.07",
	},
	{
		id = 101,
		name = "Double sandstone slab",
		hardness = 6,
		touchness = 1,
		tooltype = "pickaxe",
		parent = 100,
	},
	{
		id = 102,
		name = "Clay",
		hardness = 3,
		tooltype = "spade",
	},
	{
		id = 103,
		name = "Clay ball",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 104,
		name = "Brick",
		attached = "y -1",
		nonsolid = true,
	},
	{
		id = 105,
		name = "Oven-N",
		hardness = 8,
		tooltype = "pickaxe",
	},
	{
		id = 106,
		name = "Oven-S",
		hardness = 8,
		tooltype = "pickaxe",
	},
	{
		id = 107,
		name = "Oven-E",
		hardness = 8,
		tooltype = "pickaxe",
	},
	{
		id = 108,
		name = "Oven-W",
		hardness = 8,
		tooltype = "pickaxe",
	},
	{
		id = 109,
		name = "Bricks slab",
		hardness = 3,
		touchness = 1,
		tooltype = "pickaxe",
		mergeInto = 110,
		merger = 109,
		mergeFace = "AwayY",
		nonsolid = true,
		breakScale = "1.07 0.57 1.07",
	},
	{
		id = 110,
		name = "Double bricks slab",
		hardness = 6,
		touchness = 1,
		tooltype = "pickaxe",
		parent = 109,
	},
	{
		id = 111,
		name = "Bedrock2",
		unbreakable = true,
	},
}